### ISSUE TITLE
Example is blank

### ISSUE THREAD

**Issue by sakroy** [iatek/jquery-socialist#3]
The example - index.html - loads a blank page in all browsers.
This doesn't work.

Please, fix it.

Thanks.

**Comment by sakroy** [comment]
I managed to get it to work in another page. 

But the example in the zip file displays blank.

**Comment by jamesabruce** [comment]
You need to add jquery to the source. A silly oversight perhaps, but an easy fix.

**Comment by bschnur** [comment]
UPDATE: I copied a different but seemingly equivalent example, and it now works.  No, I don't know why.  You can see it in action at the link I posted below.

Including jquery doesn't fix this for me.  I've tried examples, as well as an example I modified to only use Twitter, which I have tried with in1dotcom as the id, as well as others.

I have set isotope to false, so that dependency shouldn't be an issue.

EDIT: I should mention, I am using Chrome, and have also used FireFox to test the page at this URL: <a href="http://fitzfallstar.com/BenSchnur/Test_Socialist/socialistExample.html">http://fitzfallstar.com/BenSchnur/Test_Socialist/socialistExample.html</a>

**Comment by Gornova** [comment]
hi! I've same problem too, easy fix:

change:

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>

to

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>

or just copy jquery on your local folder

**Comment by iatek** [comment]
Resolved by making sure you include jQuery -- from google CDN or local works
